DataTo/Controllers/UserController.cs
namespace DataTo.Controllers
{
    using System;
    using System.Linq;
    using System.Security.Cryptography;
    using System.Text;
    using System.Web;
    using System.Web.Mvc;
    using Data.Domain;
    using DataTo.Models;
    using Services.Interfaces;
    using Services.Services;

    // GET: User
    public class UserController : AdminController
    {
        private readonly IUserService serviceUser = new UserService();

        public ActionResult Index()
        {
            var users = this.serviceUser.GetAllUsers();

            var model = users.Select(user => new ListUserViewModel()
            {
                Id = user.Id,
                NameComplete = user.FirstName + " " + user.LastName,
            }).ToList();

            return this.View("Index", model);
        }

        public ActionResult Details(int id)
        {
            var user = this.serviceUser.GetById(id);

            var viewModel = new UserViewModel();

            viewModel.FirstName = user.FirstName;

            viewModel.LastName = user.LastName;

            return this.View("Details", viewModel);
        }

        public ActionResult Create()
        {
            var viewModel = new UserViewModel();

            return this.View("Create", viewModel);
        }

        [HttpPost]
        public ActionResult Create(UserViewModel model)
        {
            int idUser = this.serviceUser.IdbyName(model.UsuarioLogeado);
            if (this.ModelState.IsValid)
            {
                // valida nombre usuario unico
                int duplicado = this.serviceUser.uniconombre(model.LoginName);

                if (duplicado == 1) // usuario repetido
                {
                    this.ViewBag.Error = "Usuario Duplicado";
                }
                else
                {
                    // crea un hash con el usuario y password y lo guarda en password
                    string hashpass = Helper.EncodePassword(string.Concat(model.LoginName, model.Password));

                    var user = this.MapUser(model, idUser, hashpass);

                    this.serviceUser.Create(user);

                    return this.RedirectToAction("Index");
                }
            }

            return this.View(model);
        }

        public ActionResult Edit(int id)
        {
            var user = this.serviceUser.GetById(id);

            UserViewModel viewModel = this.MapUserViowModel(user);

            return this.View("Edit", viewModel);
        }

        [HttpPost]
        public ActionResult Edit(UserViewModel model)
        {
            int idUser = this.serviceUser.IdbyName(model.UsuarioLogeado);
            if (this.ModelState.IsValid)
            {
                model.LoginName.ToLower();

                // crea un hash con el usuario y password y lo guarda en password
                string hashpass = Helper.EncodePassword(string.Concat(model.LoginName, model.Password));

                User user = this.MapUser(model, idUser, hashpass);

                this.serviceUser.Update(user);

                return this.RedirectToAction("Index");
            }

            return this.View(model);
        }

        private User MapUser(UserViewModel model, int idUser, string hashpass)
        {
            User response = new User()
            {
                Id = model.Id,
                FirstName = model.FirstName,
                LastName = model.LastName,
                Password = hashpass,
                EditDate = DateTime.Now,
                EditUserId = idUser,
                LoginName = model.LoginName,
                AccessLevel = model.AccessLevel,
                CreateDate = model.CreateDate,
                CreateUserId = model.CreateUserId,
            };

            return response;
        }

        private UserViewModel MapUserViowModel(User user)
        {
            UserViewModel response = new UserViewModel
            {
                FirstName = user.FirstName,
                LastName = user.LastName,
                LoginName = user.LoginName,
                AccessLevel = user.AccessLevel,
                CreateDate = user.CreateDate,
                CreateUserId = user.CreateUserId,
            };

            return response;
        }

        // encriptacion de la password
        internal class Helper
        {
            public static string EncodePassword(string originalPassword)
            {
                SHA1 sha1 = new SHA1CryptoServiceProvider();
                byte[] inputBytes = new UnicodeEncoding().GetBytes(originalPassword);
                byte[] hash = sha1.ComputeHash(inputBytes);
                return Convert.ToBase64String(hash);
            }
        }

        /// <summary>
        /// Obtiene el id del usuario logueado
        /// </summary>
        /// <returns></returns>
        private int GetIdUserLog()
        {
            string logUser = System.Web.HttpContext.Current.User.Identity.Name.ToString();
            int idlogUser = this.serviceUser.IdbyName(logUser);

            return idlogUser;
        }
    }
}

DataTo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Log-Off", "LogOff", "Account")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Data log and graph Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

DataTo/Views/Shared/_LayoutAdmin.cshtml
<!doctype html>
<html lang="en-US">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <title>TallerControl 1.0 Admin</title>
    <meta name="description" content="" />
    <meta name="Author" content="Paschiero/Rocchia" />
    <link rel="icon" href="~/favicons.ico" type="image/x-icon">

    <!-- mobile settings -->
    <meta name="viewport" content="width=device-width, maximum-scale=1, initial-scale=1, user-scalable=0" />

    <!-- WEB FONTS -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700,800&amp;subset=latin,latin-ext,cyrillic,cyrillic-ext" rel="stylesheet" type="text/css" />

    <!-- CORE CSS -->
    <link href="/assetsAdmin/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />

    <!-- THEME CSS -->
    <link href="/assetsAdmin/css/essentials.css" rel="stylesheet" type="text/css" />
    <link href="/assetsAdmin/css/layout.css" rel="stylesheet" type="text/css" />
    <link href="/assetsAdmin/css/color_scheme/green.css" rel="stylesheet" type="text/css" id="color_scheme" />


</head>

<body>

    <!-- WRAPPER -->
    <div id="wrapper" class="clearfix">

        <!--
            ASIDE
            Keep it outside of #wrapper (responsive purpose)
        -->
        <aside id="aside">
            <!--

            -->
            <nav id="sideNav">
                <!-- MAIN MENU -->
                <ul class="nav nav-list">
                    <li class="active">
                        <!-- dashboard -->
                        <a class="dashboard" href="/Home/Index?page=0">
                            <!-- warning - url used by default by ajax (if eneabled) -->
                            <i class="main-icon glyphicon glyphicon-home"></i> <span>Index</span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="fa fa-menu-arrow pull-right"></i>
                            <i class="main-icon glyphicon glyphicon-user"></i> <span>Usuarios</span>
                        </a>
                        <ul>
                            <!-- submenus -->
                            <li>@Html.ActionLink("Listado", "Index", "User")</li>
                            <li>@Html.ActionLink("Crear nuevo Usuario", "Create", "User")</li>
                        </ul>
                    </li>
                </ul>


            </nav>

            <span id="asidebg"><!-- aside fixed background --></span>
        </aside>
        <!-- /ASIDE -->
        <!-- HEADER -->
        <header id="header">

            <!-- Mobile Button -->
            <button id="mobileMenuBtn" class="active"></button>

            <!-- Logo -->
            <span class="logo pull-left">
                <img src="~/Content/Images/logo.png" alt="admin panel" height="35" />
            </span>

            <nav>
                <!-- OPTIONS LIST -->
                <ul class="nav pull-right">

                    <!-- USER OPTIONS -->
                    <li class="dropdown pull-left">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                            <img class="user-avatar" alt="" src="~/assetsAdmin/images/noavatar.jpg" height="34" />
                            <span class="user-name">
                                <span class="hidden-xs" id="UserNameLog">
                                    @HttpContext.Current.User.Identity.Name.ToString() <i class="fa fa-angle-down"></i>
                                </span>
                            </span>
                        </a>
                        <ul class="dropdown-menu hold-on-click">

                            <li>
                                <!-- logout -->
                                <a href="/Account/LogOff"><i class="fa fa-power-off"></i>Log Out</a>
                            </li>
                        </ul>
                    </li>
                    <!-- /USER OPTIONS -->
                </ul>
                <!-- /OPTIONS LIST -->
            </nav>

        </header>
        <!-- /HEADER -->
        <!--
            MIDDLE
        -->
        <section id="middle">
            <div class="margin-left-50 margin-right-50">
                @RenderBody()
            </div>

            <!------------------MODALES------------------------>
            <div class="modal fade" tabindex="-1" role="dialog" id="modalAdmin" aria-labelledby="smallModal" aria-hidden="true">
                <div class="modal-dialog modal-sm" role="document" name="modalDelete">
                    <div class="modal-content" id="modalData">
                    </div>
                </div>
            </div>
            <!------------------------------------------------->
        </section>
        <!-- /MIDDLE -->

    </div>

    <footer id="footer" align="center">
        Taller de motos by SigelSoftware ®
    </footer>


    <!-- JAVASCRIPT FILES -->
    <script type="text/javascript">var plugin_path = '/assetsAdmin/plugins/';</script>

    <script type="text/javascript" src="/assetsAdmin/plugins/jquery/jquery-2.2.3.min.js"></script>
    <script type="text/javascript" src="/assetsAdmin/js/app.js"></script>

    <script src="~/assets/plugins/bootstrap.datepicker/js/bootstrap-datepicker.js"></script>
    @*$('.datepicker').datepicker();*@

    <!-- PAGE LEVEL SCRIPT -->
    <script type="text/javascript">

        loadScript(plugin_path + "jquery/jquery.cookie.js", function () {
            loadScript(plugin_path + "jquery/jquery-ui.min.js", function () {
                loadScript(plugin_path + "jquery/jquery.ui.touch-punch.min.js", function () {
                    loadScript(plugin_path + "moment.js", function () {
                        loadScript(plugin_path + "bootstrap.dialog/dist/js/bootstrap-dialog.min.js", function () {
                            loadScript(plugin_path + "fullcalendar/fullcalendar.js", function () {
                                loadScript(plugin_path + "fullcalendar/gcal.js", function () {

                                    // Load Calendar Demo Script
                                    loadScript("/assetsAdmin/js/view/demo.calendar.js");

                                });
                            });
                        });
                    });
                });
            });
        });


    </script>
    @RenderSection("scripts", required: false)
    @Scripts.Render("~/Scripts/Admin")
</body>
</html>